#if !canImport(ObjectiveC)
import XCTest

extension GamePerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GamePerformanceTests = [
        ("testValidMoves", testValidMoves),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GamePerformanceTests.__allTests__GamePerformanceTests),
    ]
}
#endif
