#if !canImport(ObjectiveC)
import XCTest

extension BitboardTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BitboardTests = [
        ("testSubscript", testSubscript),
    ]
}

extension UInt128Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UInt128Tests = [
        ("testLeftShift", testLeftShift),
        ("testRightShift", testRightShift),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BitboardTests.__allTests__BitboardTests),
        testCase(UInt128Tests.__allTests__UInt128Tests),
    ]
}
#endif
